### ISSUE TITLE
Swerve Code / Yet Another General Swerve Library (YAGSL) ⭐

### ISSUE THREAD

**Issue by tee-bee** [frc2423/2024#5]

**Comment by awordforthat** [comment]
Starting setup documentation:

0. The repo is located here: https://github.com/BroncBotz3481/YAGSL. This is just for reference, you don't need to go there yet.

1.  First, install the NavX library. Go here: https://pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/
2. Click on this `latest build` link and download the installer. 
![image](https://github.com/frc2423/2024/assets/11887852/daf7f56f-1f6b-4e32-b51d-a99878f8e9f2)
3. Find where the downloaded folder is on your computer. Right click on it and select "Extract" or "Extract all"
4. Once the files are extracted, you should see this: ![image](https://github.com/frc2423/2024/assets/11887852/6460ee8f-9cee-4a41-9f8c-e005f9861a08)
5. Double-click `setup.exe`
6. If Windows complains at you, click "Run anyway" ![image](https://github.com/frc2423/2024/assets/11887852/c566d4ca-7b8f-4b8e-9634-923f75d84a77)
7. Click through the installer: Next/Start/etc. until the installation completes. Click "Finish"

More to follow!

**Comment by amorygalili** [comment]
Swerve TODO for Saturday (1/20)

Check that:

- [ ] All Absolute Encoder's spin counterclockwise positive.
- [ ] Magnetic Absolute encoders have a good read on the magnet while still and in operation (while the robot moves).
- [ ] Absolute Encoders have unique CAN ID's or Analog Input Channel's.
- [ ] Absolute Encoder are defined with the correct ID or Analog Input Channel.

While testing on Thursday Anna and I observed in the frc web components dashboard that the swerve module angles were mirrored on the y-Axis. This is likely due to enoder values increasing clockwise. This can be changed by adding `absoluteEncoderInverted: true` to the swerve module configurations: https://yagsl.gitbook.io/yagsl/configuring-yagsl/configuration/swerve-module-configuration#example-configuration

Other things to check for swerve code:
- [ ] Make sure frc web components dashboard swerve matches what we observe on the robot
- [ ] Make sure odometry shows correct robot position (units should be checked that they scale correctly too)

We need to update the YAGSL code to use the 2024 release. I think the best way to this would be to:
- [ ] redownload the YAGSL-Example code
- [ ] Remove the [swervelib](https://github.com/BroncBotz3481/YAGSL-Example/tree/main/src/main/java/swervelib) folder and replace with the YAGSL vendordep here: https://yagsl.gitbook.io/yagsl/configuring-yagsl/dependency-installation#vendor-urls
- [ ] Copy our swerve configuration to the redownloaded example code
- [ ] Copy any additional code changes we'd like to keep to the redownloaded example code

We should also create a separate working configuration for sim. The configuration here should work: https://github.com/BroncBotz3481/YAGSL-Example/tree/main/src/main/deploy/swerve/neo We should conditionally set which configuration we use based on our environment using the `RobotBase.isSimulation()` function.

**Comment by amorygalili** [comment]
We may need to update the encoder conversion factor using this formula:

`Motor conversion factor is (PI * WHEEL DIAMETER IN METERS) / (GEAR RATIO * ENCODER RESOLUTION)`

Wheel diameters = 3 in
Gear ratio = 5.08
Encoder Resolution = 7168 or 1 if revlib already handles this for us
